--- #YAML:1.0
name:               KiokuX-User
version:            0.01
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    KiokuDB:              0.09
    Moose:                0.63
    MooseX::Types::Authen::Passphrase:  0
    namespace::clean:     0
    Sub::Exporter:        0
    Test::use::ok:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
